name: FilmModu Selenium Scraper

on:
  schedule:
    - cron: '0 */6 * * *' # 6 saatte bir
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Chrome Tarayıcıyı Kur
        uses: browser-actions/setup-chrome@latest

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4

      - name: Botu Çalıştır
        run: python scraper3.py

      - name: Commit ve Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Güncelleme: M3U8 ve VTT linkleri eklendi"
          file_pattern: "*.json *.m3u"
          branch: main
