name: Update TRGoals Playlist

on:
  schedule:
    - cron: '0 */3 * * *' # 3 Saatte bir çalışır
  workflow_dispatch: # Manuel tetikleme

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install requests beautifulsoup4

      - name: Run TRGoals Scraper
        run: python scraper2.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Dosyalar var mı kontrol et
          if [ -f trgoals.json ]; then
            git add trgoals.json trgoals.m3u
            git diff --staged --quiet || (git commit -m "TRGoals Güncelleme: $(date +'%Y-%m-%d %H:%M')" && git push)
          else
            echo "Dosyalar oluşturulmamış, pas geçiliyor."
          fi
